# Generated by Django 4.2.1 on 2023-07-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='planter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('nic', models.CharField(max_length=15)),
                ('estate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estate.estate')),
            ],
        ),
    ]
