# Generated by Django 4.2.1 on 2023-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planter', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planter',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
