# Generated by Django 4.2.1 on 2023-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planter', '0003_alter_planter_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='planter',
            name='estate_number',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
