# Generated by Django 4.2.1 on 2023-07-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
        ('planter', '0004_planter_estate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planter',
            name='estate_number',
        ),
        migrations.AddField(
            model_name='planter',
            name='estate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estate.estate'),
        ),
    ]
