# Generated by Django 4.2.1 on 2023-07-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planter', '0007_alter_planter_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planter',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
