# Generated by Django 4.2.1 on 2023-07-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_alter_estate_estatename_alter_estate_teatype'),
        ('planter', '0008_alter_planter_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planter',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.estate'),
        ),
    ]
