# Generated by Django 4.2.1 on 2023-07-29 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicles_routename_remove_vehicles_routes'),
        ('collector', '0003_rename_customuser_collector_user'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='day',
        ),
        migrations.RemoveField(
            model_name='route',
            name='ended_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='started_time',
        ),
        migrations.AddField(
            model_name='route',
            name='routename',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='vehicles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.collector')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
        ),
    ]
