# Generated by Django 4.2.1 on 2023-07-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_remove_route_day_remove_route_ended_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20),
        ),
    ]
