# Generated by Django 4.2.1 on 2023-07-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_alter_routedetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Sunday', 'Sunday')], max_length=20),
        ),
    ]
