# Generated by Django 4.2.1 on 2023-07-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_alter_routedetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Tuesday', 'Tuesday')], max_length=20),
        ),
    ]
