# Generated by Django 4.2.1 on 2023-07-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_alter_routedetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday')], max_length=20),
        ),
    ]
