# Generated by Django 4.2.1 on 2023-07-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0009_alter_routedetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20),
        ),
    ]
