# Generated by Django 4.2.1 on 2023-07-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0015_alter_routedetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Friday', 'Friday'), ('Monday', 'Monday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday')], max_length=20),
        ),
    ]
