# Generated by Django 4.2.1 on 2023-07-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0019_alter_routedetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday')], max_length=20),
        ),
    ]
