# Generated by Django 4.2.1 on 2023-07-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0021_alter_routedetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Sunday', 'Sunday')], max_length=20),
        ),
    ]
