# Generated by Django 4.2.1 on 2023-07-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0022_alter_routedetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Monday', 'Monday'), ('Sunday', 'Sunday')], max_length=20),
        ),
    ]
