# Generated by Django 4.2.1 on 2023-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0023_alter_routedetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday')], max_length=20),
        ),
    ]
