# Generated by Django 4.2.1 on 2023-07-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0031_alter_routedetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20),
        ),
    ]
