# Generated by Django 4.2.1 on 2023-08-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0032_alter_routedetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedetails',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Monday', 'Monday')], max_length=20),
        ),
    ]
