# Generated by Django 4.2.3 on 2023-07-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetArrivals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collectionpointname', models.CharField(max_length=30)),
                ('collectionpoint', models.CharField(max_length=30)),
                ('arrivaltime', models.CharField(max_length=30)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=30)),
            ],
        ),
    ]
