# Generated by Django 4.2.1 on 2023-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetArrivals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collectionpointname', models.CharField(max_length=30)),
                ('arrivaltime', models.CharField(max_length=30)),
                ('day', models.CharField(choices=[('Monday', 'monday'), ('Tuesday', 'tuesday'), ('Wednesday', 'wednesday'), ('Thursday', 'thursday'), ('Friday', 'friday'), ('Saturday', 'saturday'), ('Sunday', 'sunday')], max_length=30)),
            ],
        ),
    ]
