# Generated by Django 4.2.1 on 2023-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_arrivals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setarrivals',
            name='day',
            field=models.CharField(choices=[('Monday', 'monday'), ('Tuesday', 'tuesday'), ('Wednesday', 'wednesday'), ('Thursday', 'thursday'), ('Friday', 'friday'), ('Saturday', 'saturday'), ('Sunday', 'sunday')], max_length=30),
        ),
    ]
