# Generated by Django 4.2.1 on 2023-07-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set_arrivals', '0002_alter_setarrivals_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setarrivals',
            name='collectionpoint',
        ),
    ]
