# Generated by Django 4.2.1 on 2023-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_arrivals', '0003_remove_setarrivals_collectionpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='setarrivals',
            name='collectionpoint',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
