# Generated by Django 4.2.1 on 2023-07-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set_arrivals', '0004_setarrivals_collectionpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setarrivals',
            name='arrivaltime',
        ),
    ]
