# Generated by Django 4.2.1 on 2023-07-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set_arrivals', '0005_remove_setarrivals_arrivaltime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setarrivals',
            old_name='collectionpoint',
            new_name='arrivaltime',
        ),
    ]
