# Generated by Django 4.2.1 on 2023-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='estatenumber',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
