# Generated by Django 4.2.1 on 2023-07-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_estate_estatenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='estatenumber',
        ),
    ]
