# Generated by Django 4.2.1 on 2023-07-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_remove_estate_estatenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='estatename',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='teatype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
