# Generated by Django 4.2.1 on 2023-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatype', '0002_alter_teatype_teaprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teatype',
            name='teaprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
