# Generated by Django 4.2.1 on 2023-07-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planter', '0005_remove_planter_estate_number_planter_estate'),
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='planter',
            field=models.ManyToManyField(default=1, to='planter.planter'),
        ),
    ]
