# Generated by Django 4.2.1 on 2023-07-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collector',
            old_name='customuser',
            new_name='user',
        ),
    ]
