# Generated by Django 4.2.1 on 2023-07-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_collector_planter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='planter',
        ),
    ]
