# Generated by Django 4.2.1 on 2023-07-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_alter_collector_nic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collector',
            old_name='adress',
            new_name='address',
        ),
    ]
