# Generated by Django 4.2.1 on 2023-07-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_alter_collector_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
