# Generated by Django 4.2.1 on 2023-07-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_alter_collector_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
