# Generated by Django 4.2.1 on 2023-07-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclenumber', models.CharField(max_length=20)),
                ('drivername', models.CharField(max_length=20)),
                ('routename', models.CharField(max_length=20)),
                ('collector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collector.collector')),
            ],
        ),
    ]
