# Generated by Django 4.2.1 on 2023-07-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='routename',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='routes',
        ),
    ]
