# Generated by Django 4.2.1 on 2023-07-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='routes',
            field=models.ManyToManyField(to='route.route'),
        ),
    ]
