# Generated by Django 4.2.1 on 2023-07-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector', '0001_initial'),
        ('estate', '0001_initial'),
        ('payements', '0001_initial'),
        ('planter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_date', models.DateField()),
                ('weight', models.FloatField()),
                ('collector', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collector.collector')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.estate')),
                ('payments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payements.payments')),
                ('planter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planter.planter')),
            ],
        ),
    ]
