# Generated by Django 4.2.1 on 2023-06-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_number', models.CharField(max_length=4)),
                ('planter_name', models.CharField(max_length=20)),
                ('collected_date', models.DateField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
