# Generated by Django 4.2.1 on 2023-07-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='collector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collector.collector'),
        ),
    ]
