# Generated by Django 4.2.1 on 2023-07-29 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='estate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estate.estate'),
        ),
    ]
