# Generated by Django 4.2.1 on 2023-07-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='payments',
        ),
    ]
