# Generated by Django 4.2.1 on 2023-07-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_remove_updates_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='got_paid',
            field=models.BooleanField(default=False),
        ),
    ]
