# Generated by Django 4.2.1 on 2023-07-29 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_updates_estate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='estate',
        ),
    ]
