# Generated by Django 4.2.1 on 2023-07-29 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teatype', '0001_initial'),
        ('updates', '0002_remove_updates_payments'),
        ('payements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='amount',
            new_name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='priceperkg',
        ),
        migrations.AddField(
            model_name='payments',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='teatype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='teatype.teatype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='updates.updates'),
            preserve_default=False,
        ),
    ]
