# Generated by Django 4.2.1 on 2023-07-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0003_alter_payments_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
