# Generated by Django 4.2.1 on 2023-07-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0004_alter_payments_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.FloatField(null=True),
        ),
    ]
