# Generated by Django 4.2.1 on 2023-07-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0005_alter_payments_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='calculated_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
