# Generated by Django 4.2.1 on 2023-07-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0006_payments_calculated_amount_alter_payments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='gross_weight',
            field=models.FloatField(null=True),
        ),
    ]
