# Generated by Django 4.2.1 on 2023-07-30 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teatype', '0001_initial'),
        ('payements', '0009_payments_planter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='teatype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teatype.teatype'),
        ),
    ]
