# Generated by Django 4.2.1 on 2023-07-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0011_alter_payments_teatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='teatype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
