# Generated by Django 4.2.1 on 2023-07-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0013_alter_payments_calculated_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='gross_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
