# Generated by Django 4.2.1 on 2023-07-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0014_alter_payments_gross_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='teatype',
        ),
    ]
