# Generated by Django 4.2.1 on 2023-07-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0015_remove_payments_teatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='got_paid',
            field=models.BooleanField(default=False),
        ),
    ]
