# Generated by Django 4.2.1 on 2023-07-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0016_payments_got_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
    ]
